# voir https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    # Notez que la session ne sera démarrée QUE si vous y lisez ou y écrivez.
    session:
        enabled: true
        cookie_secure: auto
        cookie_httponly: true

    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
