
vich_uploader:
   db_driver: orm
   mappings:
       service_images:
           uri_prefix: /uploads/services
           upload_destination: '%kernel.project_dir%/public/uploads/services'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
