global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'php'
    static_configs:
      - targets: ['php:9003'] # Cible : exportateur PHP-FPM
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
